import { createContext, useContext, useState, useEffect } from "react";
import PropTypes from "prop-types";

const LanguageContext = createContext();

export const DICTIONARY = {
  id: {
    backToIsland: "Kembali ke Pulau",
    soundOn: "Suara: Aktif (Klik untuk matikan)",
    soundOff: "Suara: Mati (Klik untuk nyalakan)",
    // Home Island Zones
    homeEyebrow: "Catatan Pembuka",
    gateKicker: "Catatan Pembuka",
    gateTitle: "Sebuah pulau kecil di waktu senja.",
    gateSubtitle: "Langit senja dan diorama pulau sudah siap untuk dijelajahi.",
    gateButton: "Menuju Pulau →",
    gateLoading: "Memuat aset pulau...",
    zone1Eyebrow: "Catatan Pembuka",
    zone1Name: "Diorama Pulau",
    zone2Name: "Kabin Kerja",
    zone3Name: "Observatorium",
    zone4Name: "Reaktor Mesin",
    zone5Name: "Mercusuar",
    zone1Title: "Sebuah pulau kecil di waktu senja.",
    zone1Sub: "Selamat datang! Saya Raka, software engineer yang suka meracik hal-hal interaktif. Telusuri pulau lewat navigasi di bawah untuk melihat karya, riset, dan eksperimen yang pernah saya bangun.",
    zone1Prompt: "Jelajahi pulau untuk melihat apa yang saya bangun.",
    zone1AllProjects: "Mulai Tur",
    zone1About: "Baca Profil",
    zone1Action: "Mulai Tur",
    zonePrev: "Sebelumnya",
    zoneNext: "Selanjutnya",
    zonePrevAria: "Zona Sebelumnya",
    zoneNextAria: "Zona Selanjutnya",
    mobilePrevAria: "Zona Sebelumnya",
    mobileNextAria: "Zona Selanjutnya",
    mobileNavAria: "Navigasi zona mobile",
    desktopNavAria: "Navigasi zona pulau",
    mobileOpenPrefix: "Buka",
    zone2Eyebrow: "Kabin Kerja",
    zone2Title: "Tentang Saya",
    zone2Desc: "Cerita di balik layar, perjalanan ngoding, dan apa aja yang biasa saya kerjakan sehari-hari.",
    zone2Cta: "Kenalan Lebih Dekat",
    zone2Action: "Buka Halaman",
    zone3Eyebrow: "Observatorium",
    zone3Title: "Riset & Prestasi",
    zone3Desc: "Eksplorasi yang berujung juara: AI Singapore 2025 dan Google Gemma 3n Challenge di Kaggle.",
    zone3Cta: "Lihat Penghargaan",
    zone3Action: "Lihat Awards",
    zone4Eyebrow: "Reaktor Mesin",
    zone4Title: "Proyek & Lab",
    zone4Desc: "Mulai dari bot trading Solana sampai game on-chain multi-chain. Kode beneran yang jalan di produksi.",
    zone4Cta: "Lihat Semua Proyek",
    zone4Action: "Buka Proyek",
    zone5Eyebrow: "Mercusuar Pantai",
    zone5Title: "Ngobrol Yuk",
    zone5Desc: "Mau ngobrolin proyek baru, nanya-nanya hal teknis, atau sekadar say hi? Pintu selalu terbuka.",
    zone5Cta: "Kirim Pesan",
    zone5Action: "Kirim Pesan",
    // About Page
    aboutEyebrow: "Tentang",
    aboutIntro: "Saya software engineer yang fokus bikin web modern, responsif, dan enak dipakai. Sehari-hari banyak ngoprek frontend, arsitektur terdesentralisasi (Web3 seperti Solana & ICP), sampai eksplorasi AI praktis. Senang membangun produk dari nol hingga stabil di produksi.",
    awardsTitle: "Prestasi & Penghargaan",
    awardsKicker: "Pencapaian",
    awardsSub: "Beberapa kompetisi internasional dan program akselerasi yang pernah saya selesaikan.",
    awardWinnerBadge: "Pemenang",
    skillsTitle: "Keahlian Teknis",
    skillsKicker: "Keahlian",
    skillsHeading: "Perangkat & Ekosistem",
    skillsSub: "Teknologi dan tools yang biasa saya pakai sehari-hari buat bangun aplikasi dari frontend sampai server.",
    skillsCountSuffix: "teknologi",
    expTitle: "Riwayat Pengalaman",
    expKicker: "Perjalanan",
    expHeading: "Pengalaman Kerja",
    expSub: "Tempat saya belajar, berkontribusi di produksi, dan memecahkan masalah nyata bareng tim.",
    originOpsTitle: "Peran Operasional & Kreatif",
    originOpsKicker: "Fondasi Operasional",
    originOpsHeading: "Sebelum Full di Kode",
    originOpsSub: "Pengalaman operasional lapangan, jaringan, dan produksi konten yang bikin saya paham dunia nyata di luar layar.",
    // Projects Page
    projectsEyebrow: "Portofolio",
    projectsTitle: "Proyek Pilihan",
    projectsIntro: "Kumpulan proyek nyata yang pernah saya bikin — mulai dari infrastruktur trading Solana, integrasi blockchain multi-chain, sampai web apps yang dipakai pengguna aktif.",
    filterAll: "Semua",
    catWeb3: "Web3 & Crypto",
    catFullstack: "Fullstack & SaaS",
    catAi: "AI & Inovasi",
    projectDefaultCategory: "Proyek",
    productionBadge: "Produksi",
    viewDetails: "Lihat Detail",
    visitProject: "Kunjungi",
    projectDetailAria: "Detail proyek {name}",
    openProjectLinkAria: "Buka tautan proyek",
    collabEyebrow: "Kolaborasi",
    collabAboutTitle: "Tertarik bikin sesuatu bareng?",
    collabAboutDesc: "Terbuka untuk diskusi proyek baru, konsultasi frontend & Web3, atau sekadar bertukar pikiran.",
    collabProjectsTitle: "Punya ide seru yang pengen diwujudin?",
    collabProjectsDesc: "Yuk ngobrol santai. Siapa tahu kita bisa kolaborasi dan bikin sesuatu yang berdampak.",
    collabCta: "Hubungi saya →",
    drawerEyebrow: "Spesifikasi Proyek",
    drawerCloseAria: "Tutup detail proyek",
    drawerCloseBtn: "Tutup (ESC)",
    drawerCategoryLabel: "Kategori:",
    drawerOverviewHeading: "Ikhtisar & Sasaran",
    drawerTechHeading: "Teknologi & Modul",
    drawerStatusHeading: "Status Implementasi",
    drawerStatusLabel: "Status:",
    drawerStatusValue: "Tersedia di Produksi",
    drawerArchLabel: "Arsitektur:",
    drawerArchDefault: "Modular",
    drawerOpenLink: "Buka Tautan Langsung",
    // Contact Page
    contactEyebrow: "Kontak",
    contactTitle: "Kirim Pesan",
    contactIntro: "Ada ide proyek, tawaran kerja bareng, atau pengen nanya-nanya? Tulis aja di bawah, saya usahakan balas secepatnya.",
    nameLabel: "Nama Lengkap",
    namePlaceholder: "mis. Raka Fantino",
    emailLabel: "Alamat Email",
    emailPlaceholder: "nama@domain.com",
    messageLabel: "Pesan Anda",
    messagePlaceholder: "Ceritakan ide proyekmu, pertanyaan teknis, atau apa aja yang pengen diobrolin...",
    sendBtn: "Kirim Pesan",
    sendingBtn: "Mengirim pesan...",
    errNameRequired: "Nama wajib diisi.",
    errEmailRequired: "Alamat email wajib diisi.",
    errEmailInvalid: "Format email tidak valid.",
    errMessageRequired: "Pesan tidak boleh kosong.",
    errMessageTooLong: "Pesan melebihi batas {max} karakter.",
    statusReady: "Siap menerima pesanmu",
    statusReadyDesc: "Formulir siap. Pesan akan diteruskan langsung ke kotak masuk email saya.",
    statusTyping: "Sedang menulis pesan",
    statusTypingDesc: "{count} karakter telah diketik dalam formulir.",
    statusError: "Gagal mengirim pesan",
    statusErrorValidation: "Mohon lengkapi dan perbaiki isian formulir di sebelah kiri.",
    statusErrorGateway: "Gateway pengiriman tidak merespons. Silakan periksa koneksi dan coba lagi.",
    statusTransmitting: "Mengirim pesan…",
    statusTransmittingDesc: "Menghubungkan ke gateway pengiriman email...",
    statusSuccess: "Pesan terkirim ✓",
    statusSuccessDesc: "Pesan Anda telah berhasil sampai di kotak masuk saya.",
    statusSuccessDescMock: "Pesan terkirim dalam mode simulasi demo terverifikasi.",
    statusBadgeIdle: "Siap",
    statusBadgeTyping: "Menulis",
    statusBadgeTransmitting: "Mengirim",
    statusBadgeSuccess: "Terkirim",
    statusBadgeError: "Gagal",
    terminalStatusHeader: "Status Pengiriman",
    terminalStatusPrefix: "Status:",
    terminalTargetEmailLabel: "Email Tujuan:",
    terminalCharCountLabel: "Jumlah Karakter:",
    terminalGatewayLabel: "Kanal Layanan:",
    terminalGatewayEmailJS: "EmailJS Gateway",
    terminalGatewayMock: "Mode demo (tanpa EmailJS)",
    terminalPrivacyNote: "Privasi terjaga",
    terminalMockNote: "Simulasi demo aktif",
    terminalDirectNote: "Langsung ke kotak masuk",
    alertSuccessReal: "Pesan terkirim dengan sukses!",
    alertSuccessMock: "Pesan terkirim (Mode simulasi demo terverifikasi).",
    alertFailed: "Pesan gagal terkirim. I didn't receive your message.",
    tourStep1Title: "Diorama Workshop",
    tourStep1Desc: "Ini miniatur dunia kerja saya — pulau ini merangkum proyek, riset, dan eksperimen yang pernah saya bangun.",
    tourStep2Title: "Navigasi Astrolabe",
    tourStep2Desc: "Gunakan jarum kompas perunggu ini untuk berpindah dari satu zona ke zona lainnya.",
    tourStep3Title: "Instrumen Kompas",
    tourStep3Desc: "Nyalakan musik suasana senja dan ganti bahasa kapan saja lewat instrumen ini.",
    tourStep4Title: "Tandai Peta",
    tourStep4Desc: "Ekspedisi siap dimulai! Mari mulai dengan mengunjungi Kabin Kerja.",
    tourSkip: "Lewati",
    tourNext: "Lanjut →",
    tourFinish: "Mulai Ekspedisi →",
  },
  en: {
    backToIsland: "Back to Island",
    soundOn: "Sound: ON (Click to mute)",
    soundOff: "Sound: OFF (Click to unmute)",
    // Home Island Zones
    homeEyebrow: "Opening Notes",
    gateKicker: "Opening Notes",
    gateTitle: "A small workshop island at dusk.",
    gateSubtitle: "The sunset sky and island diorama are primed and ready to explore.",
    gateButton: "Enter Island →",
    gateLoading: "Loading island assets...",
    zone1Eyebrow: "Opening Notes",
    zone1Name: "Island Diorama",
    zone2Name: "Workshop Cabin",
    zone3Name: "Observatory",
    zone4Name: "Machine Reactor",
    zone5Name: "Lighthouse",
    zone1Title: "A small workshop island at dusk.",
    zone1Sub: "Welcome! I'm Raka, a software engineer who crafts interactive things. Explore the island using the controls below to discover projects, research, and experiments I've built.",
    zone1Prompt: "Spin the island to explore what I've built.",
    zone1AllProjects: "Start Tour",
    zone1About: "Read Profile",
    zone1Action: "Start Tour",
    zonePrev: "Previous",
    zoneNext: "Next",
    zonePrevAria: "Previous Zone",
    zoneNextAria: "Next Zone",
    mobilePrevAria: "Previous Zone",
    mobileNextAria: "Next Zone",
    mobileNavAria: "Mobile zone navigation",
    desktopNavAria: "Island zone navigation",
    mobileOpenPrefix: "Open",
    zone2Eyebrow: "Workshop Cabin",
    zone2Title: "About Me",
    zone2Desc: "The story behind the screen: my engineering journey, daily workflow, and what drives my craft.",
    zone2Cta: "Get to Know Me",
    zone2Action: "Open Page",
    zone3Eyebrow: "Observatory",
    zone3Title: "Research & Awards",
    zone3Desc: "Curious experiments that won prizes: AI Singapore 2025 and Google Gemma 3n Challenge on Kaggle.",
    zone3Cta: "View Awards & Honors",
    zone3Action: "View Awards",
    zone4Eyebrow: "Machine Reactor",
    zone4Title: "Projects & Lab",
    zone4Desc: "From high-speed Solana trading bots to multi-chain on-chain games. Real code running in production.",
    zone4Cta: "Explore All Projects",
    zone4Action: "Open Projects",
    zone5Eyebrow: "Coastal Lighthouse",
    zone5Title: "Say Hello",
    zone5Desc: "Have a project in mind, technical questions, or just want to connect? My inbox is always open.",
    zone5Cta: "Drop a Message",
    zone5Action: "Send Message",
    // About Page
    aboutEyebrow: "About",
    aboutIntro: "I'm a software engineer building fast, responsive, and delightful web applications. Most of my days are spent crafting modern frontends, decentralized systems (Solana & ICP), and practical AI integrations. I love taking products from zero to stable production.",
    awardsTitle: "Honors & Achievements",
    awardsKicker: "Achievements",
    awardsSub: "A few international competitions and acceleration programs under my belt.",
    awardWinnerBadge: "Winner",
    skillsTitle: "Technical Arsenal",
    skillsKicker: "Expertise",
    skillsHeading: "Tools & Ecosystem",
    skillsSub: "Core technologies and daily drivers I use to build systems from the browser to the backend.",
    skillsCountSuffix: "technologies",
    expTitle: "Work Experience",
    expKicker: "Journey",
    expHeading: "Work Experience",
    expSub: "Where I've shipped code, solved real problems, and grown alongside great teams.",
    originOpsTitle: "Operations & Creative Background",
    originOpsKicker: "Operational Foundation",
    originOpsHeading: "Before Full-Time Code",
    originOpsSub: "Field operations, network infrastructure, and media production that taught me how real-world systems run.",
    // Projects Page
    projectsEyebrow: "Portfolio",
    projectsTitle: "Featured Projects",
    projectsIntro: "Real products I've engineered — from Solana trading tools and blockchain games to fullstack web applications with active users.",
    filterAll: "All",
    catWeb3: "Web3 & Crypto",
    catFullstack: "Fullstack & SaaS",
    catAi: "AI & Innovation",
    projectDefaultCategory: "Project",
    productionBadge: "Production",
    viewDetails: "View Details",
    visitProject: "Visit",
    projectDetailAria: "View details for {name}",
    openProjectLinkAria: "Open project link in new tab",
    collabEyebrow: "Collaboration",
    collabAboutTitle: "Want to build something together?",
    collabAboutDesc: "Always open to explore new projects, Web3 architecture, or technical advisory.",
    collabProjectsTitle: "Have an exciting idea to bring to life?",
    collabProjectsDesc: "Let's chat. We might build something impactful together.",
    collabCta: "Contact me →",
    drawerEyebrow: "Project Specifications",
    drawerCloseAria: "Close project details",
    drawerCloseBtn: "Close (ESC)",
    drawerCategoryLabel: "Category:",
    drawerOverviewHeading: "Overview & Objectives",
    drawerTechHeading: "Tech Stack & Modules",
    drawerStatusHeading: "Implementation Status",
    drawerStatusLabel: "Status:",
    drawerStatusValue: "Live in Production",
    drawerArchLabel: "Architecture:",
    drawerArchDefault: "Modular",
    drawerOpenLink: "Open Direct Link",
    // Contact Page
    contactEyebrow: "Contact",
    contactTitle: "Get in Touch",
    contactIntro: "Have a project, job opportunity, or just want to connect? Drop a line below and I'll get back to you soon.",
    nameLabel: "Full Name",
    namePlaceholder: "e.g. Raka Fantino",
    emailLabel: "Email Address",
    emailPlaceholder: "name@domain.com",
    messageLabel: "Your Message",
    messagePlaceholder: "Tell me about your project, timeline, or whatever's on your mind...",
    sendBtn: "Send Message",
    sendingBtn: "Sending message...",
    errNameRequired: "Name is required.",
    errEmailRequired: "Email address is required.",
    errEmailInvalid: "Invalid email format.",
    errMessageRequired: "Message cannot be empty.",
    errMessageTooLong: "Message exceeds {max} characters limit.",
    statusReady: "Ready for transmission",
    statusReadyDesc: "Form is primed. Inquiries will be forwarded directly to my primary inbox.",
    statusTyping: "Drafting message",
    statusTypingDesc: "{count} characters typed in form.",
    statusError: "Transmission failed",
    statusErrorValidation: "Please correct the highlighted form fields on the left.",
    statusErrorGateway: "Transmission gateway did not respond. Check your connection and retry.",
    statusTransmitting: "Transmitting message…",
    statusTransmittingDesc: "Connecting to email delivery gateway...",
    statusSuccess: "Message Delivered!",
    statusSuccessDesc: "Your message has reached my primary inbox successfully.",
    statusSuccessDescMock: "Message delivered in verified demo simulation mode.",
    statusBadgeIdle: "Ready",
    statusBadgeTyping: "Drafting",
    statusBadgeTransmitting: "Sending",
    statusBadgeSuccess: "Delivered",
    statusBadgeError: "Failed",
    terminalStatusHeader: "Transmission Status",
    terminalStatusPrefix: "Status:",
    terminalTargetEmailLabel: "Recipient Email:",
    terminalCharCountLabel: "Character Count:",
    terminalGatewayLabel: "Service Channel:",
    terminalGatewayEmailJS: "EmailJS Gateway",
    terminalGatewayMock: "Demo mode (without EmailJS)",
    terminalPrivacyNote: "Privacy protected",
    terminalMockNote: "Demo simulation active",
    terminalDirectNote: "Direct to inbox",
    alertSuccessReal: "Message sent successfully!",
    alertSuccessMock: "Message sent (Verified demo simulation mode).",
    alertFailed: "Transmission failed. I didn't receive your message.",
    tourStep1Title: "Workshop Diorama",
    tourStep1Desc: "This is my miniature workshop world — summarizing projects, research, and experiments I've built.",
    tourStep2Title: "Astrolabe Navigation",
    tourStep2Desc: "Use these forged bronze compass needles to navigate from zone to zone.",
    tourStep3Title: "Compass Instruments",
    tourStep3Desc: "Tune the sunset ambient sound and switch languages anytime via these instruments.",
    tourStep4Title: "Chart the Map",
    tourStep4Desc: "Expedition ready! Let us begin by visiting the Workshop Cabin.",
    tourSkip: "Skip",
    tourNext: "Next →",
    tourFinish: "Start Expedition →",
  },
};

export const LANGUAGES = {
  id: "ID",
  en: "EN",
};

export const resolveTranslation = (lang, target) => {
  if (target && typeof target === "object") {
    return target[lang] ?? target.id ?? "";
  }
  return DICTIONARY[lang]?.[target] || DICTIONARY.id[target] || target;
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("portfolio_lang") || "id";
    }
    return "id";
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("portfolio_lang", lang);
    }
  }, [lang]);

  const toggleLang = () => {
    setLang((prev) => (prev === "id" ? "en" : "id"));
  };

  const t = (keyOrObject) => {
    return resolveTranslation(lang, keyOrObject);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

LanguageProvider.propTypes = {
  children: PropTypes.node.isRequired,
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      lang: "id",
      setLang: () => {},
      toggleLang: () => {},
      t: (k) => resolveTranslation("id", k),
    };
  }
  return context;
};
